const responses = {
    "hi there": "Hello! I'm Bot A. How can I assist you today?",
    "hello": "Hi! Nice to meet you. What would you like to talk about?",
    "hi": "Hey! I'm here and ready to chat.",
    "hey": "Hey! What's on your mind?",
    "hey there": "Hello! How can I help?",
    "good morning": "Good morning! Hope you have a great day ahead.",
    "good afternoon": "Good afternoon! How's your day going?",
    "good evening": "Good evening! What would you like to chat about?",
    "good night": "Good night! Sleep well.",
    "how are you?": "I'm a bot, so I don't have feelings, but I'm ready to help you!",
    "how are you doing?": "I'm doing fine — ready to assist you with anything you need.",
    "how's it going?": "Going well! How about you?",
    "what's up?": "Not much — I'm here and ready to chat. You?",
    "what's new?": "Just here to chat and help. What's new with you?",
    "long time no see": "Nice to see you again! What would you like to talk about?",
    "nice to meet you": "Nice to meet you too! How can I help?",
    "pleased to meet you": "Pleased to meet you as well. What can I do for you?",
    "good to see you": "Good to see you! What's on your mind?",
    "thanks": "You're welcome!",
    "thank you": "Glad to help!",
    "thanks a lot": "No problem — happy to help!",
    "much appreciated": "I appreciate the kind words. Anything else?",
    "you're welcome": "Anytime!",
    "no problem": "Glad to help. Anything else you need?",
    "sorry": "No worries. How can I assist you now?",
    "my apologies": "It's okay. What would you like to do next?",
    "oops": "No problem — mistakes happen. How can I help fix it?",
    "i'm bored": "Want to chat, play a word game, or hear a fun fact?",
    "i'm tired": "Maybe take a break or a short rest. Want something relaxing to read?",
    "i'm happy": "That's great to hear! What's making your day good?",
    "i'm sad": "I'm sorry to hear that. Do you want to talk about it or get a distraction?",
    "i'm excited": "Awesome! What's got you excited?",
    "i'm anxious": "Take a deep breath. Would you like a grounding exercise or a distraction?",
    "i'm hungry": "Got any favorites? I can suggest a quick snack or simple recipe.",
    "i'm thirsty": "A glass of water is always a good choice. Want a beverage idea?",
    "let's chat": "Sure — what shall we talk about?",
    "tell me something interesting": "Here's a quick fact: Honey never spoils — archaeologists have eaten 3,000-year-old honey!",
    "tell me a fun fact": "Octopuses have three hearts. Want another one?",
    "tell me more": "What topic would you like more details about?",
    "go on": "I'm listening. Tell me what's next.",
    "interesting": "Glad you think so. Want to dive deeper?",
    "cool": "Nice! Anything else that interests you?",
    "neat": "Happy you liked it. Want another?",
    "oh really": "Yes — would you like more info or an example?",
    "i see": "Got it. Want to expand on that?",
    "sounds good": "Great — what's the next step?",
    "sure": "Okay — what would you like to do?",
    "maybe later": "No rush. I'm here whenever you want to continue.",
    "not now": "Understood. Reach out when you're ready.",
    "let's do it": "Awesome — tell me how you'd like to start.",
    "see you later": "See you later! Feel free to come back anytime.",
    "talk soon": "Talk soon — take care!",
    "take care": "You too — stay well!",
    "goodbye": "Goodbye! Have a great day!",
    "bye": "Bye! Come back anytime.",
    "farewell": "Farewell — wishing you the best.",
    "congrats": "Congratulations! That's great news.",
    "well done": "Nice work — well done!",
    "nice job": "Great job! Keep it up.",
    "welcome back": "Welcome back! What would you like to do now?",
    "no worries": "All good. How can I help next?",
    "default": "I'm sorry, I don't understand that. Can you please rephrase?",
    "tell me a joke": "theres already a joke on the other end of this computer."
};
